# Generated by Django 4.1.5 on 2023-03-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
        migrations.AlterField(
            model_name="employee",
            name="company_name",
            field=models.CharField(max_length=60),
        ),
    ]
