# Generated by Django 4.1.5 on 2023-03-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auth_system",
            "0006_remove_employee_leave_date_employee_leave_end_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee_leave",
            name="End_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="End Date (dd/mm/yyyy)"
            ),
        ),
    ]
