# Generated by Django 4.1.5 on 2023-03-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0008_alter_employee_leave_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee_leave",
            name="End_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="End Date (yyyy-mm-dd)"
            ),
        ),
        migrations.AlterField(
            model_name="employee_leave",
            name="Start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Start Date (yyyy-mm-dd)"
            ),
        ),
    ]
