# Generated by Django 4.1.5 on 2023-03-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_system", "0012_alter_employee_leave_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="leave_available",
            field=models.PositiveIntegerField(default=30, editable=False),
        ),
    ]
